### ISSUE TITLE
HorizontalBlockSpreadGrower significant performance impact

### ISSUE THREAD

**Issue by wingzero54** [CivMC/RealisticBiomes#29]
With paper timing you can see RBChunkCache is causing lag spikes https://timings.aikar.co/?id=5271943e14a540e185696badebc89914 and with a Spark sampler you can drill down and see it's entirely due to HorizontalBlockSpreadGrower https://spark.lucko.me/huKnJZlT39. 

Currently WIP by IceKeeper and Psygate

**Comment by psygate** [comment]
For now, directly dependend on https://github.com/CivMC/RealisticBiomes/issues/30

**Comment by Aleksey-Terzi** [comment]
HorizontalBlockSpreadGrower needs to be fully reworked.
1. It has significant performance issues
2. It allows duplications

The workaround for this issue is proposed in #30 via using huge mushrooms.

I propose to postpone this issue and return back when the time will permit.

**Comment by wingzero54** [comment]
We mitigated this issue by just making mushrooms grow vanilla, but that is not a long-term solution
